// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: taotao/agent/v1/agent.proto

// Wire definition for the taotao-agent service.
//
// One service · 3 RPCs · same handler serves three protocols at once
// (gRPC, gRPC-Web, Connect/JSON) when generated with buf + connect-go.
//
// Protocol cheatsheet:
//
//	gRPC          — high-throughput service-mesh callers (Go/Java/Rust services)
//	gRPC-Web      — browsers behind an Envoy/proxy
//	Connect/JSON  — anyone with curl: `POST /taotao.agent.v1.AgentService/Chat`
//	                with `Content-Type: application/json` and a JSON body
//
// All three reuse the same server implementation in internal/server/.
package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/doraemonlyz-jpg/taotao-agent/clients/go-client/proto/taotao/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "taotao.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceChatProcedure is the fully-qualified name of the AgentService's Chat RPC.
	AgentServiceChatProcedure = "/taotao.agent.v1.AgentService/Chat"
	// AgentServiceChatStreamProcedure is the fully-qualified name of the AgentService's ChatStream RPC.
	AgentServiceChatStreamProcedure = "/taotao.agent.v1.AgentService/ChatStream"
	// AgentServiceHealthProcedure is the fully-qualified name of the AgentService's Health RPC.
	AgentServiceHealthProcedure = "/taotao.agent.v1.AgentService/Health"
)

// AgentServiceClient is a client for the taotao.agent.v1.AgentService service.
type AgentServiceClient interface {
	// Unary · send a message · get the full reply.
	// Internally collects every token from ChatStream into one string.
	Chat(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error)
	// Server-streaming · sends ChatStreamResponse messages as they happen
	// (session → tokens → traces → done).  The wire shape mirrors the SSE
	// events the Python backend publishes — one envelope, oneof payload.
	ChatStream(context.Context, *connect.Request[v1.ChatStreamRequest]) (*connect.ServerStreamForClient[v1.ChatStreamResponse], error)
	// Cheap probe · used by k8s liveness/readiness and the docker healthcheck.
	// Does NOT touch the LLM.
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewAgentServiceClient constructs a client for the taotao.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_taotao_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		chat: connect.NewClient[v1.ChatRequest, v1.ChatResponse](
			httpClient,
			baseURL+AgentServiceChatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Chat")),
			connect.WithClientOptions(opts...),
		),
		chatStream: connect.NewClient[v1.ChatStreamRequest, v1.ChatStreamResponse](
			httpClient,
			baseURL+AgentServiceChatStreamProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ChatStream")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+AgentServiceHealthProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	chat       *connect.Client[v1.ChatRequest, v1.ChatResponse]
	chatStream *connect.Client[v1.ChatStreamRequest, v1.ChatStreamResponse]
	health     *connect.Client[v1.HealthRequest, v1.HealthResponse]
}

// Chat calls taotao.agent.v1.AgentService.Chat.
func (c *agentServiceClient) Chat(ctx context.Context, req *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error) {
	return c.chat.CallUnary(ctx, req)
}

// ChatStream calls taotao.agent.v1.AgentService.ChatStream.
func (c *agentServiceClient) ChatStream(ctx context.Context, req *connect.Request[v1.ChatStreamRequest]) (*connect.ServerStreamForClient[v1.ChatStreamResponse], error) {
	return c.chatStream.CallServerStream(ctx, req)
}

// Health calls taotao.agent.v1.AgentService.Health.
func (c *agentServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the taotao.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// Unary · send a message · get the full reply.
	// Internally collects every token from ChatStream into one string.
	Chat(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error)
	// Server-streaming · sends ChatStreamResponse messages as they happen
	// (session → tokens → traces → done).  The wire shape mirrors the SSE
	// events the Python backend publishes — one envelope, oneof payload.
	ChatStream(context.Context, *connect.Request[v1.ChatStreamRequest], *connect.ServerStream[v1.ChatStreamResponse]) error
	// Cheap probe · used by k8s liveness/readiness and the docker healthcheck.
	// Does NOT touch the LLM.
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_taotao_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceChatHandler := connect.NewUnaryHandler(
		AgentServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(agentServiceMethods.ByName("Chat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceChatStreamHandler := connect.NewServerStreamHandler(
		AgentServiceChatStreamProcedure,
		svc.ChatStream,
		connect.WithSchema(agentServiceMethods.ByName("ChatStream")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceHealthHandler := connect.NewUnaryHandler(
		AgentServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(agentServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taotao.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceChatProcedure:
			agentServiceChatHandler.ServeHTTP(w, r)
		case AgentServiceChatStreamProcedure:
			agentServiceChatStreamHandler.ServeHTTP(w, r)
		case AgentServiceHealthProcedure:
			agentServiceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Chat(context.Context, *connect.Request[v1.ChatRequest]) (*connect.Response[v1.ChatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taotao.agent.v1.AgentService.Chat is not implemented"))
}

func (UnimplementedAgentServiceHandler) ChatStream(context.Context, *connect.Request[v1.ChatStreamRequest], *connect.ServerStream[v1.ChatStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("taotao.agent.v1.AgentService.ChatStream is not implemented"))
}

func (UnimplementedAgentServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taotao.agent.v1.AgentService.Health is not implemented"))
}
