// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: taotao/agent/v1/agent.proto

// Wire definition for the taotao-agent service.
//
// One service · 3 RPCs · same handler serves three protocols at once
// (gRPC, gRPC-Web, Connect/JSON) when generated with buf + connect-go.
//
// Protocol cheatsheet:
//
//   gRPC          — high-throughput service-mesh callers (Go/Java/Rust services)
//   gRPC-Web      — browsers behind an Envoy/proxy
//   Connect/JSON  — anyone with curl: `POST /taotao.agent.v1.AgentService/Chat`
//                   with `Content-Type: application/json` and a JSON body
//
// All three reuse the same server implementation in internal/server/.

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatStreamResponse_Kind int32

const (
	ChatStreamResponse_KIND_UNSPECIFIED ChatStreamResponse_Kind = 0
	ChatStreamResponse_KIND_SESSION     ChatStreamResponse_Kind = 1
	ChatStreamResponse_KIND_TOKEN       ChatStreamResponse_Kind = 2
	ChatStreamResponse_KIND_TRACE       ChatStreamResponse_Kind = 3
	ChatStreamResponse_KIND_DONE        ChatStreamResponse_Kind = 4
)

// Enum value maps for ChatStreamResponse_Kind.
var (
	ChatStreamResponse_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SESSION",
		2: "KIND_TOKEN",
		3: "KIND_TRACE",
		4: "KIND_DONE",
	}
	ChatStreamResponse_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_SESSION":     1,
		"KIND_TOKEN":       2,
		"KIND_TRACE":       3,
		"KIND_DONE":        4,
	}
)

func (x ChatStreamResponse_Kind) Enum() *ChatStreamResponse_Kind {
	p := new(ChatStreamResponse_Kind)
	*p = x
	return p
}

func (x ChatStreamResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatStreamResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_taotao_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ChatStreamResponse_Kind) Type() protoreflect.EnumType {
	return &file_taotao_agent_v1_agent_proto_enumTypes[0]
}

func (x ChatStreamResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatStreamResponse_Kind.Descriptor instead.
func (ChatStreamResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{3, 0}
}

type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's message · required.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Session id from a previous response · empty = start a new session.
	// Reuse to keep multi-turn memory + checkpointer continuity.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-issued (or echoed) session id · save this for the next turn.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Full concatenated agent reply · all tokens joined.
	Reply         string `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ChatStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// One event in the streaming response · matches the SSE event taxonomy.
//
//	kind = SESSION → fired ONCE at start with the server-side session id
//	kind = TOKEN   → one chunk of the user-facing reply
//	kind = TRACE   → an internal node event (planner / tool_call / ...)
//	                 payload is opaque JSON for max forward-compat
//	kind = DONE    → fired ONCE when the graph finishes
type ChatStreamResponse struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Kind  ChatStreamResponse_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=taotao.agent.v1.ChatStreamResponse_Kind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatStreamResponse_Session
	//	*ChatStreamResponse_Token
	//	*ChatStreamResponse_Trace
	//	*ChatStreamResponse_Done
	Payload       isChatStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamResponse) GetKind() ChatStreamResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return ChatStreamResponse_KIND_UNSPECIFIED
}

func (x *ChatStreamResponse) GetPayload() isChatStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatStreamResponse) GetSession() *SessionPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ChatStreamResponse) GetToken() *TokenPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *ChatStreamResponse) GetTrace() *TracePayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Trace); ok {
			return x.Trace
		}
	}
	return nil
}

func (x *ChatStreamResponse) GetDone() *DonePayload {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isChatStreamResponse_Payload interface {
	isChatStreamResponse_Payload()
}

type ChatStreamResponse_Session struct {
	Session *SessionPayload `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

type ChatStreamResponse_Token struct {
	Token *TokenPayload `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type ChatStreamResponse_Trace struct {
	Trace *TracePayload `protobuf:"bytes,4,opt,name=trace,proto3,oneof"`
}

type ChatStreamResponse_Done struct {
	Done *DonePayload `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

func (*ChatStreamResponse_Session) isChatStreamResponse_Payload() {}

func (*ChatStreamResponse_Token) isChatStreamResponse_Payload() {}

func (*ChatStreamResponse_Trace) isChatStreamResponse_Payload() {}

func (*ChatStreamResponse_Done) isChatStreamResponse_Payload() {}

type SessionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPayload) Reset() {
	*x = SessionPayload{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPayload) ProtoMessage() {}

func (x *SessionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPayload.ProtoReflect.Descriptor instead.
func (*SessionPayload) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SessionPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TokenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPayload) Reset() {
	*x = TokenPayload{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPayload) ProtoMessage() {}

func (x *TokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPayload.ProtoReflect.Descriptor instead.
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TokenPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TracePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall-clock seconds since unix epoch · 0 if not set.
	Ts float64 `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	// Which graph node fired this · executor / planner / tool_router / ...
	Node string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Event kind · tool_call / tool_result / plan / route / error / ...
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Opaque JSON-encoded payload · keep flexible across backend changes.
	// Decode client-side if you actually need fields.
	PayloadJson   string `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracePayload) Reset() {
	*x = TracePayload{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracePayload) ProtoMessage() {}

func (x *TracePayload) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracePayload.ProtoReflect.Descriptor instead.
func (*TracePayload) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TracePayload) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *TracePayload) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *TracePayload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TracePayload) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type DonePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonePayload) Reset() {
	*x = DonePayload{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonePayload) ProtoMessage() {}

func (x *DonePayload) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonePayload.ProtoReflect.Descriptor instead.
func (*DonePayload) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DonePayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Model             string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	CriticEnabled     bool                   `protobuf:"varint,3,opt,name=critic_enabled,json=criticEnabled,proto3" json:"critic_enabled,omitempty"`
	GuardrailsEnabled bool                   `protobuf:"varint,4,opt,name=guardrails_enabled,json=guardrailsEnabled,proto3" json:"guardrails_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taotao_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_taotao_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HealthResponse) GetCriticEnabled() bool {
	if x != nil {
		return x.CriticEnabled
	}
	return false
}

func (x *HealthResponse) GetGuardrailsEnabled() bool {
	if x != nil {
		return x.GuardrailsEnabled
	}
	return false
}

var File_taotao_agent_v1_agent_proto protoreflect.FileDescriptor

var file_taotao_agent_v1_agent_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74,
	0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x46,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4c, 0x0a, 0x11, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x9b, 0x03, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x3b,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x61, 0x6f,
	0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x35, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x48, 0x00, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6e, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x5d, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x0e, 0x0a,
	0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a,
	0x09, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x69, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x0b, 0x44, 0x6f, 0x6e, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72,
	0x61, 0x69, 0x6c, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x67, 0x75, 0x61, 0x72, 0x64, 0x72, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x32, 0xf7, 0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1c,
	0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74,
	0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0a, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x22, 0x2e, 0x74, 0x61, 0x6f, 0x74,
	0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1e,
	0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x59, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f,
	0x72, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x6c, 0x79, 0x7a, 0x2d, 0x6a, 0x70, 0x67, 0x2f, 0x74, 0x61,
	0x6f, 0x74, 0x61, 0x6f, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x61, 0x6f, 0x74, 0x61, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f,
	0x76, 0x31, 0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_taotao_agent_v1_agent_proto_rawDescOnce sync.Once
	file_taotao_agent_v1_agent_proto_rawDescData []byte
)

func file_taotao_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_taotao_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_taotao_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taotao_agent_v1_agent_proto_rawDesc), len(file_taotao_agent_v1_agent_proto_rawDesc)))
	})
	return file_taotao_agent_v1_agent_proto_rawDescData
}

var file_taotao_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_taotao_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_taotao_agent_v1_agent_proto_goTypes = []any{
	(ChatStreamResponse_Kind)(0), // 0: taotao.agent.v1.ChatStreamResponse.Kind
	(*ChatRequest)(nil),          // 1: taotao.agent.v1.ChatRequest
	(*ChatResponse)(nil),         // 2: taotao.agent.v1.ChatResponse
	(*ChatStreamRequest)(nil),    // 3: taotao.agent.v1.ChatStreamRequest
	(*ChatStreamResponse)(nil),   // 4: taotao.agent.v1.ChatStreamResponse
	(*SessionPayload)(nil),       // 5: taotao.agent.v1.SessionPayload
	(*TokenPayload)(nil),         // 6: taotao.agent.v1.TokenPayload
	(*TracePayload)(nil),         // 7: taotao.agent.v1.TracePayload
	(*DonePayload)(nil),          // 8: taotao.agent.v1.DonePayload
	(*HealthRequest)(nil),        // 9: taotao.agent.v1.HealthRequest
	(*HealthResponse)(nil),       // 10: taotao.agent.v1.HealthResponse
}
var file_taotao_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: taotao.agent.v1.ChatStreamResponse.kind:type_name -> taotao.agent.v1.ChatStreamResponse.Kind
	5,  // 1: taotao.agent.v1.ChatStreamResponse.session:type_name -> taotao.agent.v1.SessionPayload
	6,  // 2: taotao.agent.v1.ChatStreamResponse.token:type_name -> taotao.agent.v1.TokenPayload
	7,  // 3: taotao.agent.v1.ChatStreamResponse.trace:type_name -> taotao.agent.v1.TracePayload
	8,  // 4: taotao.agent.v1.ChatStreamResponse.done:type_name -> taotao.agent.v1.DonePayload
	1,  // 5: taotao.agent.v1.AgentService.Chat:input_type -> taotao.agent.v1.ChatRequest
	3,  // 6: taotao.agent.v1.AgentService.ChatStream:input_type -> taotao.agent.v1.ChatStreamRequest
	9,  // 7: taotao.agent.v1.AgentService.Health:input_type -> taotao.agent.v1.HealthRequest
	2,  // 8: taotao.agent.v1.AgentService.Chat:output_type -> taotao.agent.v1.ChatResponse
	4,  // 9: taotao.agent.v1.AgentService.ChatStream:output_type -> taotao.agent.v1.ChatStreamResponse
	10, // 10: taotao.agent.v1.AgentService.Health:output_type -> taotao.agent.v1.HealthResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_taotao_agent_v1_agent_proto_init() }
func file_taotao_agent_v1_agent_proto_init() {
	if File_taotao_agent_v1_agent_proto != nil {
		return
	}
	file_taotao_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ChatStreamResponse_Session)(nil),
		(*ChatStreamResponse_Token)(nil),
		(*ChatStreamResponse_Trace)(nil),
		(*ChatStreamResponse_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taotao_agent_v1_agent_proto_rawDesc), len(file_taotao_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taotao_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_taotao_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_taotao_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_taotao_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_taotao_agent_v1_agent_proto = out.File
	file_taotao_agent_v1_agent_proto_goTypes = nil
	file_taotao_agent_v1_agent_proto_depIdxs = nil
}
